version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ecomap
      POSTGRES_PASSWORD: ecomap
      POSTGRES_DB: ecomap_db

    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/posgressql

volumes:
  db: